### ISSUE TITLE
java.lang.NullPointerException in BufferedReader

### ISSUE THREAD

**Issue by MHKalantarian** [MrHTZ/PersianStemmer-Java#1]
`
try (Reader reader = new BufferedReader(new InputStreamReader(Stemmer.class.getResourceAsStream(resourceName))))
`
     Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at com.hadisaboohi.irproject.Stemmer.Stemmer.loadData(Stemmer.java:68)
        at com.hadisaboohi.irproject.Stemmer.Stemmer.loadRule(Stemmer.java:111)
        at com.hadisaboohi.irproject.Stemmer.Stemmer.<clinit>(Stemmer.java:50)

**Comment by fateme00100** [comment]
visit this website its about [best attorney in isfahan](https://hamedamiri.com/%D9%85%D9%88%D8%B3%D8%B3%D9%87-%D8%AD%D9%82%D9%88%D9%82%DB%8C-%D8%AF%D8%B1-%D8%A7%D8%B5%D9%81%D9%87%D8%A7%D9%86/) and can help you to solve your legal issues.
